# Generated by Django 5.2.4 on 2025-07-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.FloatField()),
                ('mime_type', models.CharField(max_length=50)),
                ('model_id', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
