# Generated by Django 5.2.4 on 2025-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='model',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
