# Generated by Django 5.2.4 on 2025-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_files_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file_size',
            new_name='size',
        ),
        migrations.AddField(
            model_name='files',
            name='uuid',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='model_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
