# Generated by Django 5.2.4 on 2025-07-23 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_alter_files_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
