# Generated by Django 5.2.4 on 2025-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
