# Generated by Django 5.2.4 on 2025-07-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_deleted_at_alter_quiz_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quizes',
        ),
    ]
