# Generated by Django 5.2.4 on 2025-07-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_quiz_quizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizes',
            new_name='Quizzes',
        ),
    ]
