# Generated by Django 5.2.4 on 2025-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_quizes_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_or_false', 'True or False'), ('essay', 'Essay'), ('fill_in_the_blanks', 'Fill in the blanks')], null=True)),
                ('difficulty', models.IntegerField()),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='quizzes',
            name='type',
            field=models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], max_length=10, null=True),
        ),
    ]
