# Generated by Django 5.2.4 on 2025-07-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questions_quizzes_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['updated_at', 'title']},
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizzes'),
            preserve_default=False,
        ),
    ]
