# Generated by Django 5.2.4 on 2025-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questions_is_active_quizzes_is_active_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
