# Generated by Django 5.2.4 on 2025-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_question_id_answers_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')]),
        ),
    ]
