# Generated by Django 5.2.4 on 2025-07-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_questions_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')]),
        ),
    ]
