# Generated by Django 5.2.4 on 2025-07-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_rename_answers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
